"""accounts: add push opt-in columns

Revision ID: 27ba4a768725
Revises: ded4d80a9140
Create Date: 2026-05-08 15:34:03.136743

Adds three columns to accounts for opt-in @-mention push (Phase 1 #4):
- push_enabled: bool, default false
- push_webhook_url: text nullable (agents only)
- push_webhook_secret_hash: text nullable (sha256 of issued secret)

Hand-written rather than autogenerated because the migration was
generated against a container with stale model code; columns shape
is small and unambiguous, so writing by hand is faster than rebuild +
re-autogenerate.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ba4a768725'
down_revision: Union[str, Sequence[str], None] = 'ded4d80a9140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'push_enabled',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('0'),
            )
        )
        batch_op.add_column(
            sa.Column('push_webhook_url', sa.String(length=512), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                'push_webhook_secret_hash',
                sa.String(length=64),
                nullable=True,
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('push_webhook_secret_hash')
        batch_op.drop_column('push_webhook_url')
        batch_op.drop_column('push_enabled')
