"""initial schema

Revision ID: ded4d80a9140
Revises: 
Create Date: 2026-05-06 14:26:58.354632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded4d80a9140'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('human', 'agent', name='account_kind'), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('handle', name=op.f('uq_accounts_handle'))
    )
    op.create_table('channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('public', 'private', 'dm', name='channel_kind'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('slug', name=op.f('uq_channels_slug'))
    )
    op.create_table('agent_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_agent_tokens_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_agent_tokens_token_hash'))
    )
    with op.batch_alter_table('agent_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tokens_account_id'), ['account_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_account_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_account_id'], ['accounts.id'], name=op.f('fk_audit_log_actor_account_id_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_account_id'), ['actor_account_id'], unique=False)

    op.create_table('channel_memberships',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', 'read_only', name='membership_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_channel_memberships_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_memberships_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'channel_id', name='pk_channel_memberships')
    )
    op.create_table('human_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_human_sessions_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_sessions')),
    sa.UniqueConstraint('session_hash', name=op.f('uq_human_sessions_session_hash'))
    )
    with op.batch_alter_table('human_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_sessions_account_id'), ['account_id'], unique=False)

    op.create_table('threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('root_message_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_threads_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_message_id'], ['messages.id'], name='fk_threads_root_message_id_messages', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads'))
    )
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threads_channel_id'), ['channel_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=True),
    sa.Column('reply_to', sa.Uuid(), nullable=True),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_format', sa.Enum('markdown', 'plaintext', name='body_format'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_messages_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to'], ['messages.id'], name=op.f('fk_messages_reply_to_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['accounts.id'], name=op.f('fk_messages_sender_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name=op.f('fk_messages_thread_id_threads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('file', 'image', 'embed_card', name='attachment_kind'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_attachments_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_message_id'), ['message_id'], unique=False)

    op.create_table('mentions',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_mentions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_mentions_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'account_id', name='pk_mentions')
    )
    op.create_table('reactions',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('emoji', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_reactions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_reactions_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'account_id', 'emoji', name='pk_reactions')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    op.drop_table('mentions')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_message_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_channel_id'))

    op.drop_table('messages')
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threads_channel_id'))

    op.drop_table('threads')
    with op.batch_alter_table('human_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_sessions_account_id'))

    op.drop_table('human_sessions')
    op.drop_table('channel_memberships')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_account_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('agent_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tokens_account_id'))

    op.drop_table('agent_tokens')
    op.drop_table('channels')
    op.drop_table('accounts')
    # ### end Alembic commands ###
