"""SQLAlchemy ORM models — Phase 1 schema.

Mirrors the data model in docs/DESIGN.md. Cross-DB friendly: Uuid for
ids (CHAR(36)/UUID under the hood depending on backend), JSON for
flexible structures, DateTime(timezone=True) for timestamps, Enum via
CHECK constraints on SQLite and native enum on Postgres.

Naming convention is set on the metadata so Alembic autogenerated
migrations produce stable, predictable constraint names instead of
auto-generated DB-specific ones.
"""

from __future__ import annotations

import uuid as uuid_lib
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import (
    JSON,
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    MetaData,
    PrimaryKeyConstraint,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    func,
)
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship,
)


# Stable constraint naming for Alembic autogenerate.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# --- Enums --------------------------------------------------------------

ACCOUNT_KINDS = ("human", "agent")
CHANNEL_KINDS = ("public", "private", "dm")
MEMBERSHIP_ROLES = ("admin", "member", "read_only")
BODY_FORMATS = ("markdown", "plaintext")
ATTACHMENT_KINDS = ("file", "image", "embed_card")


# --- Helpers ------------------------------------------------------------

def _uuid_pk() -> Mapped[uuid_lib.UUID]:
    return mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid_lib.uuid4,
    )


def _now_utc() -> datetime:
    return datetime.now(tz=timezone.utc)


def _ts_default() -> Mapped[datetime]:
    # Python default first → microsecond precision in SQLite (SQLite's
    # CURRENT_TIMESTAMP is only second precision, which causes confusing
    # ordering for messages posted within the same second).
    # server_default kept as a fallback for raw SQL inserts.
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_now_utc,
        server_default=func.current_timestamp(),
    )


def _ts_nullable() -> Mapped[datetime | None]:
    return mapped_column(DateTime(timezone=True), nullable=True)


# --- Tables -------------------------------------------------------------


class Account(Base):
    __tablename__ = "accounts"

    id: Mapped[uuid_lib.UUID] = _uuid_pk()
    kind: Mapped[str] = mapped_column(
        Enum(*ACCOUNT_KINDS, name="account_kind"), nullable=False
    )
    handle: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    display_name: Mapped[str] = mapped_column(String(128), nullable=False)
    email: Mapped[str | None] = mapped_column(String(255), nullable=True)
    password_hash: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        doc="Argon2 hash; humans only.",
    )
    created_at: Mapped[datetime] = _ts_default()
    archived_at: Mapped[datetime | None] = _ts_nullable()

    tokens: Mapped[list[AgentToken]] = relationship(
        back_populates="account", cascade="all, delete-orphan"
    )
    memberships: Mapped[list[ChannelMembership]] = relationship(
        back_populates="account", cascade="all, delete-orphan"
    )


class AgentToken(Base):
    __tablename__ = "agent_tokens"

    id: Mapped[uuid_lib.UUID] = _uuid_pk()
    account_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("accounts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    token_hash: Mapped[str] = mapped_column(
        String(64), nullable=False, unique=True, doc="sha256(bearer)"
    )
    scopes: Mapped[list[str]] = mapped_column(
        JSON, nullable=False, default=list, doc='e.g. ["channel:family-ops:post"]'
    )
    created_at: Mapped[datetime] = _ts_default()
    last_used_at: Mapped[datetime | None] = _ts_nullable()
    revoked_at: Mapped[datetime | None] = _ts_nullable()

    account: Mapped[Account] = relationship(back_populates="tokens")


class HumanSession(Base):
    __tablename__ = "human_sessions"

    id: Mapped[uuid_lib.UUID] = _uuid_pk()
    account_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("accounts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    session_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    created_at: Mapped[datetime] = _ts_default()
    last_used_at: Mapped[datetime | None] = _ts_nullable()
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class Channel(Base):
    __tablename__ = "channels"

    id: Mapped[uuid_lib.UUID] = _uuid_pk()
    slug: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    name: Mapped[str] = mapped_column(String(128), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    kind: Mapped[str] = mapped_column(
        Enum(*CHANNEL_KINDS, name="channel_kind"), nullable=False
    )
    created_at: Mapped[datetime] = _ts_default()
    archived_at: Mapped[datetime | None] = _ts_nullable()

    memberships: Mapped[list[ChannelMembership]] = relationship(
        back_populates="channel", cascade="all, delete-orphan"
    )


class ChannelMembership(Base):
    __tablename__ = "channel_memberships"

    account_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("accounts.id", ondelete="CASCADE"),
        nullable=False,
    )
    channel_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("channels.id", ondelete="CASCADE"),
        nullable=False,
    )
    role: Mapped[str] = mapped_column(
        Enum(*MEMBERSHIP_ROLES, name="membership_role"), nullable=False
    )
    joined_at: Mapped[datetime] = _ts_default()

    account: Mapped[Account] = relationship(back_populates="memberships")
    channel: Mapped[Channel] = relationship(back_populates="memberships")

    __table_args__ = (
        PrimaryKeyConstraint("account_id", "channel_id", name="pk_channel_memberships"),
    )


class Thread(Base):
    __tablename__ = "threads"

    id: Mapped[uuid_lib.UUID] = _uuid_pk()
    channel_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("channels.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # FK target added after Message is declared; configured via use_alter
    # to break the circular dependency between Thread and Message.
    root_message_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("messages.id", use_alter=True, name="fk_threads_root_message_id_messages"),
        nullable=False,
    )
    title: Mapped[str | None] = mapped_column(String(256), nullable=True)
    archived_at: Mapped[datetime | None] = _ts_nullable()


class Message(Base):
    __tablename__ = "messages"

    id: Mapped[uuid_lib.UUID] = _uuid_pk()
    channel_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("channels.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    thread_id: Mapped[uuid_lib.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("threads.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    reply_to: Mapped[uuid_lib.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("messages.id", ondelete="SET NULL"),
        nullable=True,
    )
    sender_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("accounts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    body: Mapped[str] = mapped_column(Text, nullable=False)
    body_format: Mapped[str] = mapped_column(
        Enum(*BODY_FORMATS, name="body_format"),
        nullable=False,
        default="markdown",
    )
    created_at: Mapped[datetime] = _ts_default()
    edited_at: Mapped[datetime | None] = _ts_nullable()
    deleted_at: Mapped[datetime | None] = _ts_nullable()


class Mention(Base):
    """Denormalized so polling agents can query 'where I'm mentioned, since cursor' cheaply."""

    __tablename__ = "mentions"

    message_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("messages.id", ondelete="CASCADE"),
        nullable=False,
    )
    account_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("accounts.id", ondelete="CASCADE"),
        nullable=False,
    )

    __table_args__ = (
        PrimaryKeyConstraint("message_id", "account_id", name="pk_mentions"),
    )


class Reaction(Base):
    __tablename__ = "reactions"

    message_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("messages.id", ondelete="CASCADE"),
        nullable=False,
    )
    account_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("accounts.id", ondelete="CASCADE"),
        nullable=False,
    )
    emoji: Mapped[str] = mapped_column(String(64), nullable=False)

    __table_args__ = (
        PrimaryKeyConstraint("message_id", "account_id", "emoji", name="pk_reactions"),
    )


class Attachment(Base):
    """Schema present from v1 even though attachments UI/API ship in v2."""

    __tablename__ = "attachments"

    id: Mapped[uuid_lib.UUID] = _uuid_pk()
    message_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("messages.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    kind: Mapped[str] = mapped_column(
        Enum(*ATTACHMENT_KINDS, name="attachment_kind"), nullable=False
    )
    url: Mapped[str] = mapped_column(Text, nullable=False)
    attachment_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSON, nullable=False, default=dict
    )


class AuditLog(Base):
    """Append-only. Privileged actions only (token issue/revoke, member add, role change,
    channel create/archive, message delete)."""

    __tablename__ = "audit_log"

    id: Mapped[uuid_lib.UUID] = _uuid_pk()
    actor_account_id: Mapped[uuid_lib.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("accounts.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    action: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    target_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    target_id: Mapped[uuid_lib.UUID | None] = mapped_column(Uuid(as_uuid=True), nullable=True)
    audit_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSON, nullable=False, default=dict
    )
    created_at: Mapped[datetime] = _ts_default()


# Make sure the type checker is happy with the cyclic forward refs above.
__all__ = [
    "Base",
    "Account",
    "AgentToken",
    "HumanSession",
    "Channel",
    "ChannelMembership",
    "Thread",
    "Message",
    "Mention",
    "Reaction",
    "Attachment",
    "AuditLog",
    "ACCOUNT_KINDS",
    "CHANNEL_KINDS",
    "MEMBERSHIP_ROLES",
    "BODY_FORMATS",
    "ATTACHMENT_KINDS",
]
